apiVersion: v1
kind: Service
metadata:
  labels:
    service: image-processor
  name: image-processor
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    service: image-processor
  type: ClusterIP
